# Generated by Django 2.0.1 on 2018-01-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangodocker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='confirmation_code',
            field=models.CharField(default='whKcVuL2gIRF9ZSfIkPTi1x57vFCBqsfC6L5B3EtZPrQF2aHvN', help_text='The random-generated code sent to the user for emailverification', max_length=50, unique=True),
        ),
    ]
